.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. online_qt test_online_qt
clean: FORCE
	$(MAKE) -C .. online_qt_clean test_online_qt_clean
check: FORCE
	$(MAKE) -C .. test_online_qt_check
online-qt online-qt.exe: FORCE
	 $(MAKE) -C .. online_qt
